POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NTgzMDU2MWZiMWI1NDQ4OTVjMWY1YzgiLCJpYXQiOjE3MDMwOTA2Njh9.gJIXK32K0vW6pGa295z_yZB90utusatwZ1s6timsvzc

{
  "title": "Joulutarinoita Vol. 5",
  "author": "Matti Luukkainen",
  "url": "www.bloglist.com/joulutarinoita",
  "likes": 1,
  "userId": "65830561fb1b544895c1f5c8"
}